apiVersion: v1
kind: Service
metadata:
  name: mediator-new
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
    - name: grpc
        port: 9091
        targetPort: 9091
  selector:
    app: mediator-new